// Generated by CoffeeScript 1.10.0
var Initializer, initialize;

initialize = function(container, app) {
  if (typeof window !== 'undefined') {
    return window.Travis = app;
  }
};

Initializer = {
  name: 'app',
  initialize: initialize
};

export {initialize};

export default Initializer;
