// Generated by CoffeeScript 1.10.0
import config from 'travis/config/environment';
var UserlikeInitializer, initialize;

initialize = function(container) {
  var userlikeData;
  return userlikeData = {};
};

UserlikeInitializer = {
  name: 'userlike',
  initialize: initialize
};

export {initialize};

export default UserlikeInitializer;
