#!/bin/sh
npm install --allow-root
bower install --allow-root

apt-get remove nodejs
apt-get purge nodejs
apt-get autoremove

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
apt-get update
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential

