# frozen_string_literal: true

$LOAD_PATH << 'lib'
task :update_emojis do
  s = Dir.glob('assets/images/emoji/*.png').map do |png|
    png.split('/', 4)[3].gsub('.png', '')
  end.map { |png| "'#{png}'" }.join(', ')
  e = "@EmojiDictionary = [#{s}]"
  File.open('assets/scripts/config/emoij.coffee', 'w') { |f| f.write(e) }
end
