#!/bin/bash

if [ "$TEST_SUITE" == "spec" ]; then
  bundle exec rspec spec
elif [ "$TEST_SUITE" == "ember" ]; then
  bundle exec rackup -s puma -p 5000 -D
  sleep 3
  ./run_jasmine.coffee http://localhost:5000/spec.html
elif [ "$TEST_SUITE" == "browser" ]; then
  curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
  gem install selenium-webdriver
  bundle exec rackup -s puma -p 5000 -D
  sleep 5
  curl -v http://localhost:4000/spec.html
  ruby script/saucelabs.rb
fi
