#!/bin/bash

set -ev

docker login -u=$QUAY_ROBOT_HANDLE -p=$QUAY_ROBOT_TOKEN quay.io;

docker-compose build web;

docker images;

docker tag travisweb_web quay.io/travisci/travis-web:$TRAVIS_BRANCH;
docker push quay.io/travisci/travis-web:$TRAVIS_BRANCH;

if [ ${TRAVIS_BRANCH} = "master" ]; then
  docker tag travisweb_web quay.io/travisci/travis-web:latest";
  docker push travisweb_web quay.io/travisci/travis-web:$TRAVIS_BRANCH";
fi

exit 0;
