#!/bin/bash

if [ "$TEST_SUITE" == "ruby" ]; then
  bundle exec rspec spec
elif [ "$TEST_SUITE" == "phantomjs" ]; then
  bundle exec rackup -s puma -p 5000 -D
  sleep 3
  phantomjs run_qunit.js http://localhost:5000/spec.html
else
  echo "Not running any tests"
fi
