#!/bin/bash

set -ev

docker-compose build web;

docker login -u=$QUAY_ROBOT_HANDLE -p=$QUAY_ROBOT_TOKEN quay.io;

docker images;

local_image=travisweb_web;
quay_image=quay.io/travisci/travis-web;

docker tag $local_image $quay_image:$TRAVIS_BRANCH;
docker push $quay_image:$TRAVIS_BRANCH;

docker tag $local_image $quay_image:${TRAVIS_COMMIT:0:7};
docker push $quay_image:${TRAVIS_COMMIT:0:7};

if [ ${TRAVIS_BRANCH} = "master" ]; then
  docker tag $local_image $quay_image:latest;
  docker push $quay_image:$TRAVIS_BRANCH;
fi

exit 0;
